- name: Deploy Docker App
  hosts: staging

  vars:
    docker_image: "souravkr7/cicd-app:latest"
    app_container_name: "myapp"
    app_port: "8081"

  tasks:

    - name: Pull Docker image
      command: docker pull {{ docker_image }}

    - name: Stop old container
      command: docker stop {{ app_container_name }}
      ignore_errors: yes

    - name: Remove old container
      command: docker rm {{ app_container_name }}
      ignore_errors: yes

    - name: Run container
      command: >
        docker run -d -p {{ app_port }}:80
        --name {{ app_container_name }}
        {{ docker_image }}
