- name: Deploy Docker App
  hosts: all

  vars:
    docker_image: "souravkr7/cicd-app:latest"
    app_container_name: "myapp-prod"
    app_port: "8082"

  tasks:
    - name: Ensure latest image is pulled
      command: docker pull {{ docker_image }}

    - name: Remove existing container if present
      command: docker rm -f {{ app_container_name }}
      ignore_errors: yes

    - name: Run container
      command: >
        docker run -d
        -p {{ app_port }}:8000
        --name {{ app_container_name }}
        --restart always
        {{ docker_image }}
